# Generated by Django 4.0.2 on 2022-12-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='WellBeingProvider',
        ),
    ]
