# Generated by Django 4.0.2 on 2022-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_file_wellbeingprovider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellbeingprovider',
            old_name='position',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='wellbeingprovider',
            old_name='age',
            new_name='cd_bairro',
        ),
        migrations.RemoveField(
            model_name='wellbeingprovider',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='wellbeingprovider',
            name='year_joined',
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='cd_equi',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='cd_regional',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='cd_rua',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='compl_end',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='conveniado',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='dep_admin',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='desativado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='dt_inaugur',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='equipament',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='fonte',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='func_24hr',
            field=models.CharField(default=11, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='func_manha',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='func_noite',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='func_tarde',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='id_equip',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='indfiscal',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='nome',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='nome_abrev',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='nome_mapa',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='nome_rua',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='nome_ruano',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='num_pred',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='observacao',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='pre_nome',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='quadr_equi',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='ramal',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='regional',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='sigla_equi',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='site',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='telefone',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='tema',
            field=models.CharField(default=111, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wellbeingprovider',
            name='tipo_equi',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
